blank_issues_enabled: true
contact_links:
  - name: Community support
    url: https://github.com/zimfw/zimfw/discussions/new
    about: Please use discussions to have conversations, ask questions and post answers
